version: '2.1'
services:
  bot:
    build: .
    volumes:
      - .:/code
      - ./storage:/data
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: healthcheck/redis:alpine
    volumes:
      - ./storage:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
